#VM settings
VM_IP = "172.28.128.17"
VM_MEMORY_MB  = "4096" #4g

Vagrant.configure(2) do |config|
  config.vm.box = "debian/buster64"  # https://app.vagrantup.com/debian/
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.provider "virtualbox" do |vb|
      vb.memory = VM_MEMORY_MB
    end
    jenkins.vm.synced_folder ".", "/vagrant", :mount_options => ["dmode=777", "fmode=666"]
    jenkins.vm.network "private_network", ip: VM_IP
    jenkins.vm.provision "docker"
    jenkins.vm.provision :shell, inline: <<-SHELL
      sudo apt-get install -y vim;
      cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys;   #copy the key to access the vm
      # installing compose 
      if [ -z "$( which docker-compose )" ] ; then
        sudo apt-get update;
        sudo apt-get install -y python3-pip;
        sudo pip3 install -U docker-compose;
      fi
      cd /vagrant;
      sudo docker-compose up -d;
    SHELL
  end
end
